### ISSUE TITLE
Soundcloud Streaming

### ISSUE THREAD

**Issue by doamatto** [KnoxDevTeam/Lavender#45]
Since we have YouTube streaming, maybe add SoundCloud?

**Comment by Incrested** [comment]
I'm researching this topic: might add in V2 or a subversion. If not, it's coming in v3.

**Comment by Incrested** [comment]
Prepping it to be added. Might not get a SC API key for awhile: def going to be something to be added via the config file.

**Comment by doamatto** [comment]
SC API keys are currently closed while they search for a better way to distribute. We need to fix music in general, first. Added as a dependency #89 via ZenHub

**Comment by Ultra03** [comment]
Closing as it doesn't look like they're changing this any time soon...
