### ISSUE TITLE
[Travis] Build Errror

### ISSUE THREAD

**Issue by Incrested** [KnoxDevTeam/Lavender#47]
Found this error while re-building on Travis.

![screenshot 2018-01-31 at 12 42 41](https://user-images.githubusercontent.com/30969346/35646527-59bf50e0-0684-11e8-82e1-35f41111151b.png)

**Comment by Incrested** [comment]
Updated the "travis.yml." That should work, but only time will tell.

**Comment by Incrested** [comment]
Travis console is still sending out some errors. Here's another screenshot under b076402.
![screenshot 2018-03-15 at 09 44 40](https://user-images.githubusercontent.com/30969346/37477669-808811d0-2835-11e8-86a8-3a1890f31c53.png)

**Comment by Incrested** [comment]
Took a template from someone else. Still causing errors: requires installed
![screenshot 2018-03-15 at 10 06 08](https://user-images.githubusercontent.com/30969346/37478875-8470f836-2838-11e8-98cf-eb1d44cb9c3a.png)
 dependencies. I'll add them later to the package.json. Here's what we need if you want to do it for me @Ultra03

**Comment by Incrested** [comment]
Worked on adding in all discord.js dependencies. Here's the issue now: https://gyazo.com/a3cd960ebb44a7707710cb0337432bb6

**Comment by Incrested** [comment]
Currently working on a new .travis.yml for the bot. Standby mates

**Comment by Incrested** [comment]
Probably misconfigured configs (travis and appveyor's yml files); if you can copy your env, since your's is working, it should work. We might need a "token" for it tho

**Comment by Incrested** [comment]
Note: I'll send Travis and other CI privs to members soon

**Comment by Ultra03** [comment]
Fixed! See #59 for more info.
