### ISSUE TITLE
All Cryptos But GRLC are Broken

### ISSUE THREAD

**Issue by Incrested** [KnoxDevTeam/Lavender#51]
Always respond with 'NaN' for value or 'undefined'. Possible a JSON error. You got this, @Ultra03 ?

**Comment by Ultra03** [comment]
Not sure what the problem is, I'll check it out. NaN means 'Not a Number' though, so could it be an issue with where we're getting the information from?

**Comment by Incrested** [comment]
I'm not positive. The person who kindly provided the API key said that it might be exclusive to GRLC (since he made it). Maybe we 'ought to find another API to use? I'll look into it.

**Comment by Incrested** [comment]
Currently in progress of solving.

**Comment by Incrested** [comment]
Fixed with new webhook mentioned in #62
