### ISSUE TITLE
Status Page Built using Jekyll that Uses Auto-Update From 'master'

### ISSUE THREAD

**Issue by Incrested** [KnoxDevTeam/Lavender#58]
So, this is the premise. We use [NarroApp/staticus](https://github.com/NarroApp/staticus) as a Jekyll-hosted page on gh-pages with it in a subdirectory of something like "../status/" When you push, we already go through Buddy.Works, Circle.CI, and AppVeyor. Using Buddy.Works, we can have it also update Jekyll. So, we could, on failure, have it report the issue to a Jekyll-based static page (like staticus) to help better inform those using Lavender.

**Comment by Ultra03** [comment]
Closing until further notice/development.
