### ISSUE TITLE
Play command crashes the bot

### ISSUE THREAD

**Issue by Ultra03** [KnoxDevTeam/Lavender#64]
Running the play command crashes the bot. It gives no output besides "Got a song request!" in console, but it just exits.

**Comment by Incrested** [comment]
Looking into right now. May have been resolved in a521bce1399893bcba77d4faf92bbfd0aa456a61

**Comment by Incrested** [comment]
Not just with m!play; with all commands. Possibly an issue with the way commands are remote executed. Looking into matters as of this time.

**Comment by Ultra03** [comment]
@Incrested I'm gonna rework the way the command modules are called and handled.

**Comment by Ultra03** [comment]
Seems to be solved after command rework (59088ad).
