### ISSUE TITLE
Enmap-Based Guild Configuration

### ISSUE THREAD

**Issue by doamatto** [KnoxDevTeam/Lavender#66]
This is required for the following issues: #56, #46, #10, #7, and #26. This will aid organization per each guild and allow guild-exclusive things such as logs in a certain channel and so on and so forth.

**Comment by Incrested** [comment]
Never have I ever touched Enmap. I'm gonna' try and do this myself anyways. Wish me luck! :P

**Comment by Incrested** [comment]
I think we ought to backlog this and, when we have the Mother Server, bring it back up and finish it off.

**Comment by doamatto** [comment]
#75 is closed so I'm closing this as well.
