### ISSUE TITLE
"Cannot find module './config.json'" when the File is There

### ISSUE THREAD

**Issue by Incrested** [KnoxDevTeam/Lavender#67]
I'm trying to run the bot again: tried removing my local copy and re-pulling to start. Added the proper bot key, tried the test one. But, it always result in the same error of the config file (which is renamed from config.ex.json to config.json or just made into a new file) is missing. It's there though. Very odd.

**Comment by Ultra03** [comment]
Fixed in 12c86a3 - the error message pointed to `hug.js`. Remember to export name in the command fill as well.
