### ISSUE TITLE
DBL, Discord Bots, Divine Discord Bot Integration

### ISSUE THREAD

**Issue by doamatto** [KnoxDevTeam/Lavender#77]

**Comment by Incrested** [comment]
We need `dblapi.js` as a dependency for Discord Bots and DBL just uses a webhook using `/api/bots/:bot_id/stats` with guild count being simply `guilds`.

APIs for both: https://discordbotlist.com/api-docs and https://discordbots.org/api/docs#jslib

**Comment by Incrested** [comment]
I'll be working on this later on: should be done today at late or tomorrow near mid-day

**Comment by Incrested** [comment]
Added in fc4ad52. No verified testing available: planned maintenance added.

**Comment by Incrested** [comment]
Gonna be fixing this one after school; I'll schedule maintenance

**Comment by doamatto** [comment]
There doesn't seem to be any guild count posted to DBL and Discord Bots, nor DDB. Going to look into it before Patch Day Friday

**Comment by doamatto** [comment]
#101 is important here

**Comment by doamatto** [comment]
These are all added.
