### ISSUE TITLE
Bandwidth Saving by Auto-Leaving Discord VCs

### ISSUE THREAD

**Issue by doamatto** [KnoxDevTeam/Lavender#88]
Have Lavender automatically leave a VC after a period of time of no one being in that VC and/or have Lavender automatically leave a VC after the queue is over. 

Both of these will help save bandwidth which is crucial with our current hosting solutions.

**Comment by doamatto** [comment]
Another way to save bandwidth is to limit video lengths to under 30 minutes. We can make a Patreon-supported function for longer videos.

**Comment by Ultra03** [comment]
Sounds like a good idea, I’ll work on this sometime this week.

**Comment by Ultra03** [comment]
>I’ll work on this sometime this week.
That's funny.

Anyways, experimental fix in 6788ddf. @doamatto can you test this?

**Comment by Ultra03** [comment]
Fully working as of 2f954d6.
