### ISSUE TITLE
hug command needs else statement

### ISSUE THREAD

**Issue by lepon01** [KnoxDevTeam/Lavender#91]
https://github.com/KnoxDevTeam/Lavender/blob/master/commands/hug.js#L8
needs

```js
if () {
} else {
}
```

otherwise

![image](https://user-images.githubusercontent.com/13886925/52308077-49b4e000-2994-11e9-8b80-8f614cf12a6c.png)

**Comment by Ultra03** [comment]
Thanks for letting us know, not sure how this got missed!

**Comment by doamatto** [comment]
@Ultra03, I'm going to re-do your commit in a titbit because the script wouldn't show a picture if I'm digesting it properly: it would go straight to the else statement after the "nill" snekfetch query. Like I said, I'll redo on the `develop` branch and then resolve the resolution of this issue.

**Comment by doamatto** [comment]
Resolved on 7bb33c4fea63b3a17040d38ee5bd17c5678b5d54 via `master` by Lucas
